#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun May 21 01:18:51 2023

@author: nick
"""
import numpy as np
import math
n=int(input())

k=1
F=np.zeros([1,n+1],dtype=int)
F[0,0:2]=1
for i in range(2,n+1):
    F[0,i]=k*F[0,i-2]+F[0,i-1]
print(F)
